---
name: linkcar
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  font_awesome_flutter: ^10.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dynamic_color: ^1.4.0
  cloud_firestore: ^3.1.17
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/