// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHomgM7cubBfikX6xiSKysEQTGXTeOr2w',
    appId: '1:238919190978:web:fab745993b6f760f726e5b',
    messagingSenderId: '238919190978',
    projectId: 'linkcar-9da0f',
    authDomain: 'linkcar-9da0f.firebaseapp.com',
    databaseURL: 'https://linkcar-9da0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'linkcar-9da0f.appspot.com',
    measurementId: 'G-F8X0T3Z27W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnA4lbD1I1oE6l6XzWBjTFcHPV762uxBQ',
    appId: '1:238919190978:android:f226868288627ee6726e5b',
    messagingSenderId: '238919190978',
    projectId: 'linkcar-9da0f',
    databaseURL: 'https://linkcar-9da0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'linkcar-9da0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uK86PGGWy0m_26XndFfrE1MzQJ-RGHc',
    appId: '1:238919190978:ios:9419549c2de7ffb9726e5b',
    messagingSenderId: '238919190978',
    projectId: 'linkcar-9da0f',
    databaseURL: 'https://linkcar-9da0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'linkcar-9da0f.appspot.com',
    iosClientId: '238919190978-ajt2rkmhp645fc2bqeu33qf2bkhorfgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkcar',
  );
}
